openapi: 3.0.0
info:
  title: API de Lectura
  version: "1.0"
paths:
  /v1/lectura:
    get:
      description: Devuelve todas las lecturas existentes en la base de datos.
      operationId: getLectura
      responses:
        200:
          description: Una lista de lecturas fue devuelta exitosamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Lectura'
        400:
          description: Error cometido al momento de hacer la petición http.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      description: Crea una lectura en la base de datos.
      operationId: createLectura
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Lectura'
      responses:
        201:
          description: Lectura creada exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lectura'
  /v1/lectura/{id}:
    get:
      description: Devuelve una lectura específica de la base de datos en base a su ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID de la lectura que se desea obtener.
      operationId: getLecturaById
      responses:
        200:
          description: La lectura con el ID solicitado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lectura'
        400:
          description: Un mensaje de error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Lectura:
      type: object
      properties:
        arduino:
          type: string
          description: El ID del arduino que toma la lectura.
        latitud:
          type: string
          description: La latitud tomada por el arduino (4 valores como máximo después del punto decimal).
        longitud:
          type: string
          description: La longitud tomada por el arduino (4 valores como máximo después del punto decimal).
        rotacion:
          type: string
          description: La rotación tomada por el arduino (4 valores como máximo después del punto decimal).
        aceleracion:
          type: string
          description: La aceleración tomada por el arduino (4 valores como máximo después del punto decimal).
      required:
        - arduino
        - latitud
        - longitud
        - rotacion
        - aceleracion
    Error:
      type: object
      properties:
        mensaje:
          type: string
          description: Mensaje de error detallando el problema.